# Generated by Django 5.1.3 on 2025-01-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('href', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pictures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'texts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PicturesOcr',
            fields=[
                ('href', models.OneToOneField(db_column='href', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wardrobe_db.pictures')),
                ('ocr_result', models.TextField()),
            ],
            options={
                'db_table': 'pictures_ocr',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pictures',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='wardrobe_db.types', to_field='typename'),
        ),
    ]
