# Generated by Django 5.1.3 on 2025-01-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('href', models.ForeignKey(db_column='href', on_delete=django.db.models.deletion.DO_NOTHING, to='wardrobe_db.pictures')),
            ],
            options={
                'db_table': 'ocr_mission',
                'managed': True,
            },
        ),
    ]
