# Generated by Django 5.2.3 on 2025-07-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_db', '0002_ocrmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
