from django.urls import path
from .views import image_views, search_views, metadata_views, ocr_views, stat_views, backup_views, message_views, diary_views

app_name = 'wardrobe_db'

urlpatterns = [
    path('search/', search_views.search, name='search'),
    path('searchhint/', search_views.searchHint, name='searchHint'),
    path('random/', image_views.random, name='random'),
    path('image/set/', image_views.setImageDetail, name='setImageDetail'),
    path('image/get/', image_views.getImageDetail, name='getImageDetail'),
    path('image/delete/', image_views.deleteImage, name='deleteImage'),
    path('text/set/', image_views.setImageText, name='setImageText'),
    path('keyword/list/', metadata_views.listKeywords, name='listKeywords'),
    path('keyword/create/', metadata_views.createKeyword, name='createKeyword'),
    path('keyword/delete/', metadata_views.deleteKeyword, name='deleteKeyword'),
    path('property/list/', metadata_views.listProperties, name='listProperties'),
    path('property/create/', metadata_views.createProperty, name='createProperty'),
    path('property/delete/', metadata_views.deleteProperty, name='deleteProperty'),
    path('statistics/', stat_views.getStatistics, name='getStatistics'),
    path('image/new/', image_views.newImage, name='newImage'),
    path('ocrmission/get/', ocr_views.getOcrMission, name='getOcrMission'),
    path('ocrmission/new/', ocr_views.newOcrMission, name='newOcrMission'),
    path('ocrmission/reset/', ocr_views.resetOcrMission, name='resetOcrMission'),
    path('ocrmission/execute/', ocr_views.excuteOcrMission, name='excuteOcrMission'),
    path('ocrmission/executeall/', ocr_views.excuteAllOcrMission, name='excuteAllOcrMission'),
    path('savedsearch/create/', search_views.saveSearchFilter, name='createSavedSearch'),
    path('savedsearch/list/', search_views.listSavedSearchFilters, name='listSavedSearch'),
    path('savedsearch/delete/', search_views.deleteSavedSearch, name='deleteSavedSearch'),
    path('savedsearch/get/', search_views.getSavedSearchFilter, name='getSavedSearch'),
    path('backup/list/', backup_views.list_backups, name='listBackups'),
    path('backup/create/', backup_views.create_backup, name='createBackup'),
    path('backup/download/', backup_views.download_backup, name='downloadBackup'),
    path('backup/delete/', backup_views.delete_backup, name='deleteBackup'),
    path('message/list/', message_views.listMessages, name='listMessages'),
    path('message/delete/', message_views.deleteMessage, name='deleteMessage'),
    path('message/read/', message_views.readMessage, name='readMessage'),
    path('message/clear_read/', message_views.clearMessage, name='clear_read'),
    path('message/stream/', message_views.streamMessages, name='streamMessages'),
    path('diary/search/', diary_views.search, name='search'),
    path('diary/get/',diary_views.getDiaryTexts, name='getDiaryTexts'),
    path('diary/new/', diary_views.newDiaryText, name='newDiaryText'),
    path('diary/delete/', diary_views.deleteDiaryText, name='deleteDiaryText'),
    path('diary/edit/', diary_views.editDiaryText, name='editDiaryText'),
]